[package]
name = "game-test"
version = "0.1.0"
edition = "2021"

[dependencies]
console_engine = "2.6.1"
rand = "0.9.0"
serde = { version = "1.0", features = ["derive"] } 
serde_json = "1.0.140"
figlet-rs = "0.1.5"
 